### PR TITLE
Set TMPDIR when sorting

### LINKED ISSUE #594: CDXJ merge error
## Backtrace

    line 8 of [PROJECT_ROOT]/lib/dor/was_crawl/dissemination/utilities.rb: run_sys_cmd
    line 37 of [PROJECT_ROOT]/lib/dor/was_crawl/cdxj_generator_service.rb: generate_cdx_for_one_warc
    line 14 of [PROJECT_ROOT]/lib/dor/was_crawl/cdxj_generator_service.rb: block in generate

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51141/faults/87026078)

### PR DESCRIPTION
**Pull request by edsu**
## Why was this change made? 🤔

When sorting CDXJ files `/tmp` will be used as temp space for sorting when the files don't fit in memory. This is usually ok, but when the CDXJ files being sorted are larger than what fits in `/tmp` an out of space error will be encoutered. Setting `TMPDIR` to the space used by CDXJ file generation uses should help solve this problem.

Closes #594

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning works properly in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

File: lib/dor/was_crawl/cdxj_merge_service.rb [hunk 1]
```diff
@@ -80,7 +80,10 @@ def clean
       def sort_env_vars
```
Comment (mjgiarlo) [inline lib/dor/was_crawl/cdxj_merge_service.rb:80]: I wonder if it's worth renaming this method (and the other one) now that its scope is expanding beyond the sort function. Not blocking, tho

**Review by mjgiarlo — APPROVED** [review]
Approve pending consideration of comment about method name drift

File: lib/dor/was_crawl/cdxj_merge_service.rb (hunk 1 above)
Comment (edsu) [reply lib/dor/was_crawl/cdxj_merge_service.rb:80]: How has its scope expanded beyond `sort_env_vars`? They are environment variables that are needed for sorting.

Comment (mjgiarlo) [reply lib/dor/was_crawl/cdxj_merge_service.rb:80]: I originally read this as "env vars to help control how strings sort," without expanding the code context in the PR, and I now see that is not what's going on here. It's "env vars pre-pended to a unix sort command." So it's all good. Merging.
