### PR TITLE
Setting tempdir for cdxj indexing

### LINKED ISSUE #545: cdxj-indexer step fails with large WARCs
This druid failed at the cdxj-indexer step: https://argo.stanford.edu/view/druid:pg273nz1527. The WARC that it failed indexing is 4.9GB.

When re-running the step, `log/cdx_indexer.log` shows:
```
Traceback (most recent call last):
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/bin/cdxj-indexer", line 8, in <module>
    sys.exit(main())
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 518, 
in main
    write_cdx_index(cmd.output, cmd.inputs, vars(cmd))
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 533, 
in write_cdx_index
    indexer.process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 214, 
in process_all
    super().process_all()
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/warcio/indexer.py", line 33, in p
rocess_all
    self.process_one(fh, out, filename)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/main.py", line 248, 
in process_one
    for record in wrap_it:
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line
 18, in buffering_record_iter
    buffer_record_content(record)
  File "/opt/app/was/.cache/pypoetry/virtualenvs/was-robot-suite-gi3TAXLu-py3.8/lib/python3.8/site-packages/cdxj_indexer/bufferiter.py", line
 95, in buffer_record_content
    shutil.copyfileobj(record.content_stream(), spool)
  File "/usr/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.8/tempfile.py", line 895, in write
    rv = file.write(s)
OSError: [Errno 28] No space left on device
```

### PR DESCRIPTION
**Pull request by lwrubel**
## Why was this change made? 🤔

Fixes #545. Can set TMPDIR to a larger partition on prod.  Will also require adding a tmpdir setting to was-robots1-prod settings in shared_configs. 

## How was this change tested? 🤨
Unit tests and QA. 

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning works properly in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

File: lib/dor/was_crawl/cdxj_generator_service.rb [hunk 1]
```diff
@@ -33,7 +33,8 @@ def cdx_file_name(warc_file_name)
       def generate_cdx_for_one_warc(warc_file_name)
         cdx_file_path  = cdx_file_name(warc_file_name)
         warc_file_path = "#{druid_base_directory}/#{warc_file_name}"
-        cmd_string = "#{Settings.cdxj_indexer.bin} #{warc_file_path} --output #{cdx_file_path} --dir-root #{Settings.was_crawl_dissemination.stacks_collections_path} --post-append 2>> log/cdx_indexer.log"
+        cmd_string = "export TMPDIR=#{Settings.cdxj_indexer.tmpdir} " \
```
Comment (justinlittman) [inline lib/dor/was_crawl/cdxj_generator_service.rb:36]: Can you just do following?
```
cmd_string = "TMPDIR=#{Settings.cdxj_indexer.tmpdir} #{Settings.cdxj_indexer.bin} #{warc_file_path} --output #{cdx_file_path} --dir-root #{Settings.was_crawl_dissemination.stacks_collections_path} --post-append 2>> log/cdx_indexer.log"
```

Comment (lwrubel) [reply lib/dor/was_crawl/cdxj_generator_service.rb]: Thanks, right, that would be simpler. Updated.

Comment (lwrubel) [reply lib/dor/was_crawl/cdxj_generator_service.rb]: @justinlittman would you look at the update when you have a chance and approve or comment?

**Review by justinlittman — APPROVED** [review]
